#! /bin/sh

# Main config

pgrep -x sxhkd >/dev/null || sxhkd &

# Workspaces

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Main config

bspc config border_width 2
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config window_gap 3

bspc config focus_follows_pointer true

sxhkd -c ~/.config/sxhkd/sxhkdrc &

xsetroot -cursor_name left_ptr &

# Commands at start up

xrandr --output HDMI-0 --primary

xrandr --output HDMI-0 --left-of DP-2

feh --bg-fill /home/breaddy/Pictures/mojave-dusk.jpg

polybar &

picom &

dunst &

fcitx -d &

nordvpn connect Warsaw &
